version: "3"
services:
  app:
    restart: always
    build:
      dockerfile: Dockerfile
    volumes:
      - ".env:/var/www/.env"
    ports:
      - 8080:80

  mysql:
    restart: always
    image: mysql:8.0.34
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql:
    driver: "local"
